In [1]:
# Now we can join the geographical files with the data produced by IPYS and make
# beautiful interactive maps \o/

In [2]:
import geopandas as gpd
import json
import pandas as pd
from pprint import pprint

#### Reads data in

In [3]:
# Code correspondence
correspondence = pd.read_csv("../output/correspondence.csv", sep=";")

In [4]:
# State correspondence only
province_correspondence = correspondence[["IPYS_level_1_name", "geo_level_1_code"]].drop_duplicates().reset_index()

In [5]:
# State data
level_1 = gpd.read_file("../output/level-1.geojson")

In [6]:
# City data
level_2 = gpd.read_file("../output/level-2.geojson")

In [7]:
# Ipys data
ipys_xls = pd.ExcelFile("../input/datos-de-ipyis.xlsx")

In [8]:
ipys_sheets = {}
for index, sheet_name in enumerate(ipys_xls.sheet_names):
    if index == 0:
        ipys_sheets['results'] = ipys_xls.parse(sheet_name)
    elif index ==   4:
        ipys_sheets['medios'] = ipys_xls.parse(sheet_name)

In [9]:
ipys_sheets['results'] = ipys_sheets['results'].drop(columns=["Unnamed: 6", "País", "Población"])

#### Putting the data together

In [10]:
# Adds the correspondence code for all the cities
ipys_sheets['results'] = ipys_sheets['results'].merge(correspondence, left_on='Municipio', right_on='IPYS_level_2_name', how='left')

In [11]:
ipys_sheets['results']

,Estado,Municipio,poblacion,total_med,Tipo desierto,Tamaño,IPYS_level_1_name,IPYS_level_2_name,geo_level_1_name,geo_level_2_name,geo_level_1_code,geo_level_2_code
0,Amazonas,Alto Orinoco (La Esmeralda),16774,18,Desierto,Pequeño,Amazonas,Alto Orinoco (La Esmeralda),Amazonas,Autónomo Alto Orinoco,VE02,VE0201
1,Amazonas,Atabapo (San Fernando de Atabapo),12492,18,Desierto,Pequeño,Amazonas,Atabapo (San Fernando de Atabapo),Amazonas,Autónomo Atabapo,VE02,VE0202
2,Amazonas,Atures (Puerto Ayacucho),155705,18,No desierto,Grande,Amazonas,Atures (Puerto Ayacucho),Amazonas,Autónomo Atures,VE02,VE0203
3,Amazonas,Autana (Isla Ratón),11902,18,Desierto,Pequeño,Amazonas,Autana (Isla Ratón),Amazonas,Autónomo Autana,VE02,VE0204
4,Amazonas,Manapiare (San Juan de Manapiare),10488,18,Desierto,Pequeño,Amazonas,Manapiare (San Juan de Manapiare),Amazonas,Manapiare,VE02,VE0206
...,...,...,...,...,...,...,...,...,...,...,...,...
361,Zulia,San Francisco,541628,23,No desierto,Grande,Zulia,San Francisco,Zulia,San Francisco,VE23,VE2317
362,Zulia,Santa Rita,68341,23,Desierto,Mediano,Zulia,Santa Rita,Zulia,Santa Rita,VE23,VE2318
363,Zulia,Semprún (Casigua El Cubo),35203,23,Desierto,Mediano,Zulia,Semprún (Casigua El Cubo),Zulia,Jesús María Semprum,VE23,VE2308
364,Zulia,Sucre (Bobures),69705,23,Desierto,Mediano,Zulia,Sucre (Bobures),Zulia,Sucre,VE23,VE2320
365,Zulia,Valmore Rodríguez (Bachaquero),61243,23,Desierto,Mediano,Zulia,Valmore Rodríguez (Bachaquero),Zulia,Valmore Rodríguez,VE23,VE2321

In [12]:
# There were some chances in the city names from the data in the previous steps.
ipys_sheets['results'][
    ipys_sheets['results'].geo_level_2_code.isna()
]

,Estado,Municipio,poblacion,total_med,Tipo desierto,Tamaño,IPYS_level_1_name,IPYS_level_2_name,geo_level_1_name,geo_level_2_name,geo_level_1_code,geo_level_2_code
21,Anzoátegui,Municipio Carvajal (Valle de Guanape),16740,26,Desierto,Pequeño,NaN,NaN,NaN,NaN,NaN,NaN
25,Anzoátegui,Santa Ana (Santa Ana),11899,26,Desierto,Pequeño,NaN,NaN,NaN,NaN,NaN,NaN
61,Barinas,Obispos (Obispos),43393,34,No desierto,Mediano,NaN,NaN,NaN,NaN,NaN,NaN
70,Bolívar,Municipio Caroní (Ciudad Guayana),978133,52,No desierto,Grande,NaN,NaN,NaN,NaN,NaN,NaN
71,Bolívar,Padre Pedro Chen (El Palmar),19913,52,Desierto Moderado,Pequeño,NaN,NaN,NaN,NaN,NaN,NaN
140,Falcón,Palmasola (Palmasola),9050,34,No desierto,Pequeño,NaN,NaN,NaN,NaN,NaN,NaN
174,Mérida,Adriani (El Vigía),170995,61,No desierto,Grande,NaN,NaN,NaN,NaN,NaN,NaN
176,Mérida,Aricagua (Aricagua),5223,61,Desierto Moderado,Pequeño,NaN,NaN,NaN,NaN,NaN,NaN
188,Mérida,Pinto Salinas (Santa Cruz de Mora),30047,61,No desierto,Mediano,NaN,NaN,NaN,NaN,NaN,NaN
189,Mérida,Pueblo Llano (Pueblo Llano),13483,61,No desierto,Pequeño,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
# Luckily, the order from the previous file was preserved. We can match them by index, simply.
missing_data_loc = ipys_sheets['results'][ipys_sheets['results'].geo_level_2_code.isna()].index

# Selects the missing data by index and assign the values of the correspondence file
columns_to_fill = ["IPYS_level_1_name", 
                   "IPYS_level_2_name", 
                   "geo_level_1_name", 
                   "geo_level_2_name", 
                   "geo_level_1_code", 
                   "geo_level_2_code"]

ipys_sheets['results'].loc[missing_data_loc, columns_to_fill] = correspondence.loc[missing_data_loc, columns_to_fill]

In [14]:
# Now we can merge it with the level_2 geographical data
level_2_results = ipys_sheets['results'].merge(level_2, left_on='geo_level_2_code', right_on='code')
level_2_results = gpd.GeoDataFrame(level_2_results)

In [15]:
# Now we can create a secondary dataframe and keep the data of interest for the level_2 geojson
level_2_results = level_2_results[['poblacion', 'Tipo desierto', 'Tamaño', 
                        'IPYS_level_1_name', 'IPYS_level_2_name', 
                        'code', 'parent_code', 'geometry']]

level_2_results = level_2_results.rename(columns={
    "Tipo desierto": "category",
    "Tamaño": "size",
    "poblacion": "population",
    "IPYS_level_1_name": "parent_name",
    "IPYS_level_2_name": "name",
})

In [16]:
level_2_results

,population,category,size,parent_name,name,code,parent_code,geometry
0,16774,Desierto,Pequeño,Amazonas,Alto Orinoco (La Esmeralda),VE0201,VE02,"POLYGON ((-64.72295 4.04437, -64.71693 4.04191..."
1,12492,Desierto,Pequeño,Amazonas,Atabapo (San Fernando de Atabapo),VE0202,VE02,"POLYGON ((-66.33494 4.26540, -66.27128 4.22420..."
2,155705,No desierto,Grande,Amazonas,Atures (Puerto Ayacucho),VE0203,VE02,"POLYGON ((-67.43503 6.18680, -67.43404 6.18646..."
3,11902,Desierto,Pequeño,Amazonas,Autana (Isla Ratón),VE0204,VE02,"POLYGON ((-66.41415 5.73555, -66.41180 5.72659..."
4,10488,Desierto,Pequeño,Amazonas,Manapiare (San Juan de Manapiare),VE0206,VE02,"POLYGON ((-65.57041 6.12598, -65.56539 6.11333..."
...,...,...,...,...,...,...,...,...
361,541628,No desierto,Grande,Zulia,San Francisco,VE2317,VE23,"POLYGON ((-71.77907 10.60355, -71.77750 10.602..."
362,68341,Desierto,Mediano,Zulia,Santa Rita,VE2318,VE23,"POLYGON ((-71.34195 10.60379, -71.33986 10.603..."
363,35203,Desierto,Mediano,Zulia,Semprún (Casigua El Cubo),VE2308,VE23,"POLYGON ((-73.12299 9.52094, -73.11043 9.51309..."
364,69705,Desierto,Mediano,Zulia,Sucre (Bobures),VE2320,VE23,"MULTIPOLYGON (((-71.22266 9.16279, -71.22208 9..."
365,61243,Desierto,Mediano,Zulia,Valmore Rodríguez (Bachaquero),VE2321,VE23,"POLYGON ((-70.78224 10.42926, -70.78057 10.427..."

#### Creates level 1 data

In [17]:
# Now we will compute more extensive data for the provinces, using groupys from the city level data
level_1_results = level_1.merge(ipys_sheets['results'], left_on='code', right_on='geo_level_1_code')

In [18]:
# Keep only the relevant columns, but renaming
level_1_results = level_1_results[['IPYS_level_1_name', 'geo_level_1_code', 'poblacion', 'total_med']]
level_1_results = level_1_results.rename(columns={
    "IPYS_level_1_name": "name",
    "geo_level_1_code": "code",
    "poblacion": "population",
    "total_med": "total_medios"
})

In [19]:
# Computing the population

# Groupby to get the total population for each state
gpby = level_1_results.groupby("code").sum().population.to_frame().reset_index()

# Join it back to the original results, discrding the old column
level_1_results = level_1_results.merge(gpby, on='code', suffixes=["_x", ""]).drop(columns=["population_x"])

/var/folders/52/vy6xx2q911l7rd368b7ngb8w0000gn/T/ipykernel_11507/3553573322.py:4: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  gpby = level_1_results.groupby("code").sum().population.to_frame().reset_index()

In [20]:
# Since the total medios are repeated on every line, we can simply drop duplicates
level_1_results = level_1_results.drop_duplicates().reset_index(drop=True)

In [21]:
level_1_results

                name  code  total_medios  population
0           Amazonas  VE02            18      213203
1         Anzoátegui  VE03            26     1824505
2              Apure  VE04            22      655007
3             Aragua  VE05            27     1915214
4            Barinas  VE06            34      992247
5            Bolívar  VE07            52     1947403
6           Carabobo  VE08            47     2610174
7            Cojedes  VE09            23      388104
8      Delta Amacuro  VE10            10      219680
9   Distrito capital  VE01            42     2093698
10            Falcón  VE11            34     1123592
11           Guárico  VE12            28      995049
12            Vargas  VE24            23      388407
13              Lara  VE13            23     2104972
14            Mérida  VE14            61     1093550
15           Miranda  VE15            38     3380776
16           Monagas  VE16            36     1053479
17     Nueva Esparta  VE17            19      666709
18        Portuguesa  VE18            19     1101065
19             Sucre  VE19            12     1138307
20           Táchira  VE20            28     1295189
21          Trujillo  VE21            29      906514
22           Yaracuy  VE22            15      777105
23             Zulia  VE23            23     4473902

In [22]:
# A function to count, for each row, how many children are in each category
def get_children_categories(parent, children):
    
    parent_ = parent.copy()
    children_ = children.copy()
            
    for index, row in parent_.iterrows():
                
        code = row.code
        
        children_subset = children_[children_.parent_code==code]
        
        children_categories = children_subset.category.value_counts().to_dict()
        
        for key, value in children_categories.items():
            
            parent_.loc[index, key] = value
        
    
    parent_ = parent_.rename(columns={
        "Desierto": "desert_children",
        "Desierto Moderado": "moderate_desert_children",
        "No desierto": "not_desert_children",
        "Sin información": "no_information_children"
    })
    
    return parent_

level_1_results = get_children_categories(parent=level_1_results, children=level_2_results)

In [23]:
# Agora vamos ler os dados de meios para adicionar os dados finais
medios = ipys_sheets['medios']

In [24]:
# Here we have a count of medios by province. Let's rename the columns and compute totals
medios_count = medios.groupby("name").medio_type.value_counts().unstack().reset_index()
medios_counts = medios_count.rename(
    columns={
        "provincia": "name",
        "Digital (Portal de noticias, periódico, tv o radio transmitido vía web)": "digital_medios",
        "Periódico (Impreso)": "print_medios",
        "Radio (AM o FM)": "radio_medios",
        "TV (Señal abierta o cable)": "tv_medios"
    })

In [25]:
# Add the medios count
level_1_results = level_1_results.merge(medios_counts, how='left')

In [26]:
# Now we simply need to retrieve an array of medios for each state
def get_medios_for_province(row, medios):
    
    name = row["name"]
    id_ = row["code"]
    
    # This will save the array of medios in a json file
    medios_in_province = medios[medios.name==name][['medio_name', 'medio_type', 'medio_nature']]
    medios_in_province = medios_in_province.to_dict(orient='records')
        
#     fname = f"../output/medios/{id_}.json"
#     with open(fname, "w+") as f:
#         json.dump(medios_in_province, f)
        
    return medios_in_province


level_1_results["medios_list"] = level_1_results.apply(get_medios_for_province, args=(medios,), axis=1)

In [27]:
# Joins back with geometries
level_1_results = level_1_results.merge(level_1, on=['code'])\
    .drop(columns="name_y")\
    .rename(columns={"name_x": "name"})

level_1_results = gpd.GeoDataFrame(level_1_results)

#### Checks output and exports geojson

In [46]:
with open("../output/finished-geojsons/level_1_results.geojson", "w+") as f:
    data = level_1_results.to_json()
    data = json.loads(data) # gpd outputs strings only
    json.dump(data, f)

In [47]:
with open("../output/finished-geojsons/level_2_results.geojson", "w+") as f:
    data = level_2_results.to_json()
    data = json.loads(data) # gpd outputs strings only
    json.dump(data, f)